#server.port=8081 => fichier properties
#fichier yml
server:
  port: 8081

spring:
  profiles:
    active: mysql


springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

